### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Genererar sammansättningen för två funktioner.


  Det vill säga om två funktioner $f $ och $g $, returnerar en ny funktion som representerar $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Den andra funktionen som ska användas.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Den första funktionen som ska användas.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: En ny funktion $h $ t. ex. för alla indata $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Indatatypen för den första funktionen som ska användas.
- uid: "'U"
  summary: Utdatatypen för den första funktionen som ska användas och indatatypen för den andra funktionen som ska användas.
- uid: "'V"
  summary: Utdatatypen för den andra funktionen som ska användas.
metadata:
  ms.openlocfilehash: 69fbd6a4fafbc61a63e41257b7100303fd48d4d4
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73223079"
