### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  Returnerar sammansättningen för två functions.


  Två Functions $f $ och $g $ returnerar en ny funktion som representerar $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Den andra funktionen som ska användas.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Den första funktionen som ska användas.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: En ny funktion $h $ t. ex. för alla indata $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Indatatypen för den första funktionen som ska användas.
- uid: "'U"
  summary: Utdatatypen för den första funktionen som ska användas och indatatypen för den andra funktionen som ska användas.
- uid: "'V"
  summary: Utdatatypen för den andra funktionen som ska användas.
metadata:
  ms.openlocfilehash: e62937fd42cb4067ca7a7947cac29a9ef539da6c
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89356753"
