### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Returnerar antalet qubits som för närvarande är tillgängliga för lån.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Returnerar antalet qubits som för närvarande är tillgängliga för användning.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Dessa funktioner ger information om miljön där Quantum-beräkningen sker.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201452"
